/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export type LanguageCode = 'en' | 'fr' | 'es' | 'ru' | 'it' | 'de' | 'ar' | 'zh' | 'pt' | 'hi';

export const languageNameMap: Record<LanguageCode, string> = {
  en: 'English',
  fr: 'French',
  es: 'Spanish',
  ru: 'Russian',
  it: 'Italian',
  de: 'German',
  ar: 'Arabic',
  zh: 'Mandarin Chinese',
  pt: 'Portuguese',
  hi: 'Hindi',
};

type Translation = {
  search: string;
  recent: string;
  madeBy: string;
  generatedBy: string;
  save: string;
};

export const translations: Record<LanguageCode, Translation> = {
  en: {
    search: 'Search',
    recent: 'Recent',
    madeBy: 'Made by',
    generatedBy: 'Generated by Gemini 2.5 Flash Image',
    save: 'Save',
  },
  it: {
    search: 'Cerca',
    recent: 'Recenti',
    madeBy: 'Creato da',
    generatedBy: 'Generato da Gemini 2.5 Flash Image',
    save: 'Salva',
  },
  fr: {
    search: 'Rechercher',
    recent: 'Récents',
    madeBy: 'Créé par',
    generatedBy: 'Généré par Gemini 2.5 Flash Image',
    save: 'Enregistrer',
  },
  es: {
    search: 'Buscar',
    recent: 'Recientes',
    madeBy: 'Hecho por',
    generatedBy: 'Generado por Gemini 2.5 Flash Image',
    save: 'Guardar',
  },
  de: {
    search: 'Suchen',
    recent: 'Letzte',
    madeBy: 'Erstellt von',
    generatedBy: 'Generiert von Gemini 2.5 Flash Image',
    save: 'Speichern',
  },
  ru: {
    search: 'Поиск',
    recent: 'Недавние',
    madeBy: 'Сделано',
    generatedBy: 'Создано Gemini 2.5 Flash Image',
    save: 'Сохранить',
  },
  ar: {
    search: 'بحث',
    recent: 'الأخيرة',
    madeBy: 'صنع من قبل',
    generatedBy: 'تم إنشاؤها بواسطة Gemini 2.5 Flash Image',
    save: 'حفظ',
  },
  zh: {
    search: '搜索',
    recent: '最近',
    madeBy: '由...制作',
    generatedBy: '由 Gemini 2.5 Flash Image 生成',
    save: '保存',
  },
  pt: {
    search: 'Pesquisar',
    recent: 'Recentes',
    madeBy: 'Feito por',
    generatedBy: 'Gerado por Gemini 2.5 Flash Image',
    save: 'Salvar',
  },
  hi: {
    search: 'खोजें',
    recent: 'हाल का',
    madeBy: 'द्वारा बनाया गया',
    generatedBy: 'Gemini 2.5 Flash Image द्वारा उत्पन्न',
    save: 'सहेजें',
  },
};